### ISSUE TITLE
Open Sourcing datasets

### ISSUE THREAD

**Issue by faizankshaikh** [KevenRFC/MLWARE2#1]
Please remove the datasets from repo. Thanks!

**Comment by KevenRFC** [comment]
Hi! I would like to know why should I remove the datasets from repo? Is it illegal?

**Comment by faizankshaikh** [comment]
The data is confidential, but it's shared to participants only at the time
of competition. Also there are licensing issues. So the data of closed
competitions is generally not shared after the competition ends.

I hope you understand

**Comment by KevenRFC** [comment]
Of course! Now, I understand better. Thank you for the advice! 

Regards
